//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPEIMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentPPEs
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int DepartmentId { get; set; }
        public int PPEId { get; set; }
        public string Status { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual PPEs PPEs { get; set; }
    }
}
