//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPEIMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetailUsers
    {
        public int Id { get; set; }
        public int RequestDetailId { get; set; }
        public int UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public int DocumentStatus { get; set; }
    
        public virtual RequestDetails RequestDetails { get; set; }
        public virtual Users Users { get; set; }
    }
}
