//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPEIMSApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestDetails()
        {
            this.RequestDetailUsers = new HashSet<RequestDetailUsers>();
        }
    
        public int Id { get; set; }
        public int RequestId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string Type { get; set; }
        public int QuantityIssued { get; set; }
        public string Comments { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Requests Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestDetailUsers> RequestDetailUsers { get; set; }
    }
}
